### ISSUE TITLE
Set default volume visibility in NEXT-100 geometry

### ISSUE THREAD

**Issue by gondiaz** [nextsw/nexus#137]
Solving this issue will provide you the hability to identify the structure of the nexus code that builds the geometry of a NEXT detector.

NEXT-100 geometry has a default visibility in nexus as shown below:

<img width="367" alt="next100-default-nexus-vis" src="https://user-images.githubusercontent.com/35993868/153388541-d1ee3127-f5d9-4490-8e2d-5ce71d558842.png">

The rendering time is very slow because the TPB coating inside the teflon mask holes in the tracking plane is being draw. This issue can be easily solved by modifying the default visibility of this volume to Invisible in the SiPM board geometry code.

With this issue I propose to change the default visibility above to another one that could help to visualice the inner elements of the detector, for example to something like or variant that might be useful for the user

<img width="367" alt="next100-ics-vis" src="https://user-images.githubusercontent.com/35993868/153389895-db13a22b-3c9d-4ef8-b54c-68a7ecee84e3.png">

**Hint/How-to-start:**

To run NEXT-100 default visibility go to nexus directory and run `./bin/nexus -i macros/NEXT100.init.mac` (Caution: this macro uses Next100OpticalGeometry instead of Next100, that does not include the external shielding geometry)

You can start modifying the energy plane visibilities, for example, in 

https://github.com/next-exp/nexus/blob/e3e292567cde778ed4c0dc89a2c9ead175d4fbeb/source/geometries/Next100TrackingPlane.cc#L145-L154

**Comment by kvjmistry** [comment]
Tackling the first issue highlighted here.
Digging into the code, I already see that the Teflon mask holes are set to invisible in `Next100SiPMBoard.cc`:

`mask_wls_logic_vol     ->SetVisAttributes(G4VisAttributes::GetInvisible());`

I still however get the following error in my visualisation:

```
ERROR: G4VSceneHandler::RequestPrimitives
  Polyhedron not available for SIPM_BOARD_MASK_WALL_WLS
  Touchable path:  WORLD 0 LAB 0 LEAD_BOX 0 STEEL_BOX 0 INNER_AIR 0 VESSEL 0 VESSEL_GAS 0 SIPM_BOARD 1 SIPM_BOARD_MASK 0 SIPM_BOARD_MASK_HOLE 0 SIPM_BOARD_MASK_WALL_WLS 0
  This means it cannot be visualized in the usual way on most systems.
  1) The solid may not have implemented the CreatePolyhedron method.
  2) For Boolean solids, the BooleanProcessor, which attempts to create
     the resultant polyhedron, may have failed.
  Try RayTracer. It uses Geant4's tracking algorithms instead.
  Drawing solid with cloud of points.
```

I found that this error message can be fixed, as suggested in this message, by setting the RayTracker to use cloud:
`/vis/viewer/set/style wireframe` to `/vis/viewer/set/style cloud`

I did not notice any change of speed of the visualisation and as you can see below, this option also changes the look of the detector changes with this option (to a format that doesn't look as good). 

before change
<img width="558" alt="image" src="https://user-images.githubusercontent.com/32701127/160918181-9ae04db3-839e-4605-bd2d-a77ce471e9d0.png">

after change
<img width="518" alt="image" src="https://user-images.githubusercontent.com/32701127/160918668-ac01be49-7a3f-4131-8c87-612fc7fcae28.png">

**Comment by kvjmistry** [comment]
Also, how does this look for an improvement on the visualization for NEXT-100 with visibility on?
<img width="659" alt="image" src="https://user-images.githubusercontent.com/32701127/160938904-5933cb6d-8ceb-4d35-8bb6-3d1cd504aa7c.png">

**Comment by gondiaz** [comment]
Might it be that you are confusing SIPM_BOARD_MASK_WLS with SIPM_BOARD_MASK_WALL_WLS?
Notice that the former is the coating over the telfon boards and the latter is the coating inside the holes its holes. 
The white drawing you see in the tracking plane corresponds preciselly to the SIPM_BOARD_MASK_WALL_WLS being draw, which is the main cause of the slow visualization..

**Comment by kvjmistry** [comment]
Aha! Yes that was it. It now runs quite a lot quicker now when I add:
`wall_wls_logic_vol     ->SetVisAttributes(G4VisAttributes::GetInvisible());`

I will make a few more updates to improve the NEXT-100 look and create a PR
