### ISSUE TITLE
Simulation of 0nubb and physics lists

### ISSUE THREAD

**Issue by gondiaz** [nextsw/nexus#149]
The simulation of 0nubb events is done through the Decay0Interface generator.
It seems that loading the physics list `NexusPhysics` as the first list in the macro init file messes up electrons with IonizationElectrons (ie-). The two 0nubb electrons are simulated as ie- which does not loose any energy, resulting in undesired output.

**Comment by paolafer** [comment]
The order of the physics lists in the macro file is important for several reasons and in many cases, not only for 0nubb events. The example macros are there to show the correct order.
