### ISSUE TITLE
Crashes due to persistency manager

### ISSUE THREAD

**Issue by jmalbos** [nextsw/nexus#156]
1. If no persistency manager (PM) is specified in the initialisation macro, NEXUS crashes due to a `FatalException`. Do we need to enforce the use of a PM? There are plenty of cases in which one is not really needed.

```
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : NexusApp()
      issued by : [NexusApp]
A persistency manager must be specified.
*** Fatal Exception *** core dump ***
 **** Track information is not available at this moment
 **** Step information is not available at this moment

-------- EEEE -------- G4Exception-END --------- EEEE -------
```

2. If no output file is specified in the configuration macro, NEXUS crashes at the end of the processing with no hint whatsoever about what has happened. We should check earlier whether the user has provided the filename or use a default.

```
### CAUGHT SIGNAL: 11 ### address: 0x10,  signal =  SIGSEGV, value =   11, description = segmentation violation. Address not mapped to object.

```

**Comment by paolafer** [comment]
PR #194 addresses this issue.
