### ISSUE TITLE
FusedSilica and FakeFusedSilica refraction indices not valid

### ISSUE THREAD

**Issue by soleti** [nextsw/nexus#216]
The formula for the refractive indices for `FusedSilica` and `FakeFusedSilica` is valid only up to ~10.7 eV. However, the values are calculated in the code up to `optPhotMaxE_`, which is set to 11.5 eV:

https://github.com/next-exp/nexus/blob/5389016be8a34058c745d53f181be3ab66cdf8a0/source/materials/OpticalMaterialProperties.h#L88

Thus, this value:

https://github.com/next-exp/nexus/blob/5389016be8a34058c745d53f181be3ab66cdf8a0/source/materials/OpticalMaterialProperties.cc#L82

is `nan` for points above 10.7 eV.

**Comment by paolafer** [comment]
Solved in #217.
