### ISSUE TITLE
City IC structure

### ISSUE THREAD

**Issue by jahernando** [nextsw/nexus#245]
Define the City IC structure

```[tasklist]
- [] the configuration parameters
- [] data selection algorithm 
- [] map creation algorithm
- [] parameter evolution
- [] define the output parameters
- [] monitoring
- [] tests and validation
```

**Comment by paolafer** [comment]
@jahernando I assume you opened this issue in the wrong repository? This is nexus, not IC :-).

**Comment by jahernando** [comment]
Sorry!

Instituto Galego de Altas Enerxías (IGFAE)
Universidade de Santiago de Compostela (USC), Spain
Departamento de Física de Partículas.
________________________________
De: Paola Ferrario ***@***.***>
Enviado: lunes, 26 de febrero de 2024 16:39
Para: next-exp/nexus ***@***.***>
Cc: HERNANDO MORATA JOSE ANGEL ***@***.***>; Mention ***@***.***>
Asunto: Re: [next-exp/nexus] City IC structure (Issue #245)


@jahernando<https://github.com/jahernando> I assume you opened this issue in the wrong repository? This is nexus, not IC :-).
