### ISSUE TITLE
City Tools

### ISSUE THREAD

**Issue by jahernando** [nextsw/nexus#246]
Tools and NBs associated with ICAROS

```[tasklist]
- [] functions to apply the correction on data (Sphronia)
- [] access and display the map data
- [] compare two runs
- [] NB step by step of the Kr calibration 
```

**Comment by paolafer** [comment]
Idem :-).

**Comment by jahernando** [comment]
No Paola, I open in IC, otherwise is something wrong somewhere!

________________________________
De: Paola Ferrario ***@***.***>
Enviado: lunes, 26 de febrero de 2024 16:46
Para: next-exp/nexus ***@***.***>
Cc: HERNANDO MORATA JOSE ANGEL ***@***.***>; Author ***@***.***>
Asunto: Re: [next-exp/nexus] City Tools (Issue #246)


Idem :-).
