### ISSUE TITLE
ICAROS data preparation

### ISSUE THREAD

**Issue by jahernando** [nextsw/nexus#247]
ICAROS data preparation, selection of the Kr events

````[tasklist]
- [] selection of 1 S1, monitoring and check efficiency
- [] selection of 1 s2, monitoring and check efficiency
- [] selection of S2 vs t-drift  band, monitoring and check
````

- returns the filtered dst and an masks associated to the different filters
- store information about the filters
- save histograms and counters

**Comment by paolafer** [comment]
Still nexus :-).
